---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: demo-app
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:staging-*
spec:
  releaseName: demo-app-staging
  chart:
    git: ssh://git@github.com/argamanza/flux-demo
    ref: master
    path: charts/demo-app
  values:
    image: argamanza/demo-app:staging-f918c4e
    replicaCount: 1
